name: Bug Report
description: Report a gameplay, tooling, or build defect.
title: "bug: <short description>"
labels:
  - type:qa
  - scope:mvp
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is broken?
      placeholder: Describe observed behavior in one or two sentences.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Repro Steps
      description: Steps to reproduce consistently.
      placeholder: |
        1. Open scene...
        2. Do action...
        3. Observe...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - blocker
        - high
        - medium
        - low
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Paste relevant log snippets and link captures.
