using RavenDevOps.Fishing.Core;
using UnityEngine;

namespace RavenDevOps.Fishing.Fishing
{
    [DisallowMultipleComponent]
    [RequireComponent(typeof(SpriteRenderer))]
    public sealed class FishingLineBridge2D : MonoBehaviour
    {
        [SerializeField] private Transform _ship;
        [SerializeField] private Transform _hook;
        [SerializeField] private float _lineThickness = 0.05f;
        [SerializeField] private float _shipOffsetY = -0.36f;
        [SerializeField] private float _minVisibleLength = 0.12f;
        [SerializeField] private bool _hideWhenTooShort = true;

        private SpriteRenderer _renderer;

        public void Configure(Transform ship, Transform hook, float lineThickness = 0.05f, float shipOffsetY = -0.36f)
        {
            _ship = ship;
            _hook = hook;
            _lineThickness = Mathf.Max(0.01f, lineThickness);
            _shipOffsetY = shipOffsetY;
        }

        private void Awake()
        {
            CacheRenderer();
        }

        private void LateUpdate()
        {
            CacheRenderer();
            if (_renderer == null || _ship == null || _hook == null)
            {
                return;
            }

            var start = _ship.position + new Vector3(0f, _shipOffsetY, 0f);
            var end = _hook.position;
            var delta = end - start;
            var length = delta.magnitude;

            if (_hideWhenTooShort && length < Mathf.Max(0.01f, _minVisibleLength))
            {
                _renderer.enabled = false;
                return;
            }

            _renderer.enabled = true;
            transform.position = start + (delta * 0.5f);
            transform.rotation = Quaternion.Euler(0f, 0f, Mathf.Atan2(delta.y, delta.x) * Mathf.Rad2Deg - 90f);

            // Solid helper sprite generated by runtime bootstrap is 2x2 world units at scale (1,1).
            var xScale = Mathf.Max(0.005f, _lineThickness * 0.5f);
            var yScale = Mathf.Max(0.01f, length * 0.5f);
            transform.localScale = new Vector3(xScale, yScale, 1f);
        }

        private void CacheRenderer()
        {
            if (_renderer == null)
            {
                _renderer = GetComponent<SpriteRenderer>();
            }
        }
    }
}
